# Generated by Django 3.2.25 on 2024-06-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('gnp', models.IntegerField()),
                ('gnp_per_capita', models.IntegerField()),
                ('is_sale', models.BooleanField(default=False)),
            ],
        ),
    ]
