# Generated by Django 3.2.25 on 2024-06-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0002_auto_20240607_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='flag_colors',
            field=models.ManyToManyField(to='mainshop.FlagColors'),
        ),
    ]
