# Generated by Django 3.2.25 on 2024-06-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0003_auto_20240620_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagcolors',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
