# Generated by Django 3.2.25 on 2024-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0004_alter_flagcolors_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_colors',
            field=models.ManyToManyField(related_name='colors', to='mainshop.FlagColors'),
        ),
    ]
