# Generated by Django 3.2.25 on 2024-07-01 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0006_auto_20240629_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creation_data',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AddField(
            model_name='cart',
            name='creating_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
