# Generated by Django 3.2.25 on 2024-07-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0008_alter_cart_creating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='mainshop.country'),
        ),
    ]
